const products = [
    {
        id: 1,
        name: 'Head Radical Pro',
        brand: 'head',
        image: '../assets/images/radical_pro.jpg',
        description: 'Ideal para jugadores avanzados que buscan equilibrio.',
        price: 320,
        stock: 5,
    },
    {
        id: 2,
        name: 'Head Radical MP',
        brand: 'head',
        image: '../assets/images/radical_mp.jpg',
        description: 'Diseñada para jugadores que necesitan control y potencia.',
        price: 280,
        stock: 6,
    },
    {
        id: 3,
        name: 'Head Gravity Pro',
        brand: 'head',
        image: '../assets/images/gravity_pro.jpg',
        description: 'Perfecta para estabilidad y golpes precisos.',
        price: 350,
        stock: 3,
    },
    {
        id: 4,
        name: 'Head Gravity Tour',
        brand: 'head',
        image: '../assets/images/gravity_tour.jpg',
        description: 'Muy popular entre jugadores de nivel intermedio.',
        price: 300,
        stock: 7,
    },
    {
        id: 5,
        name: 'Head Speed Legend',
        brand: 'head',
        image: '../assets/images/speed_pro_legend.jpg',
        description: 'Usada por profesionales por su velocidad y precisión.',
        price: 340,
        stock: 4,
    },
    {
        id: 6,
        name: 'Head Speed Pro',
        brand: 'head',
        image: '../assets/images/speed_pro.jpg',
        description: 'Gran opción para quienes buscan control y velocidad.',
        price: 310,
        stock: 5,
    },
    {
        id: 7,
        name: 'Head Speed MP',
        brand: 'head',
        image: '../assets/images/speed_mp.jpg',
        description: 'Equilibrio perfecto entre potencia y control.',
        price: 290,
        stock: 6,
    },
    {
        id: 8,
        name: 'Wilson Blade 98',
        brand: 'wilson',
        image: '../assets/images/blade_98.jpg',
        description: 'Popular por su gran sensación y estabilidad.',
        price: 330,
        stock: 4,
    },
    {
        id: 9,
        name: 'Wilson Shift 99',
        brand: 'wilson',
        image: '../assets/images/shift_99.jpg',
        description: 'Perfecta para golpes precisos y rápidos.',
        price: 270,
        stock: 7,
    },
    {
        id: 10,
        name: 'Wilson Clash 100',
        brand: 'wilson',
        image: '../assets/images/clash_100.jpg',
        description: 'Conocida por su comodidad y flexibilidad.',
        price: 260,
        stock: 8,
    },
    {
        id: 11,
        name: 'Wilson Pro Staff 97',
        brand: 'wilson',
        image: '../assets/images/pro_staff_97.jpg',
        description: 'Favorita entre jugadores que buscan precisión.',
        price: 320,
        stock: 2,
    },
];
